vich_uploader:
    metadata:
                type: attribute
    db_driver: orm
    mappings:
        event_image:
            uri_prefix:         /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer:   Vich\UploaderBundle\Naming\OrignameNamer
