#index:
#    path: /
#    controller: App\Controller\DefaultController::index


evenement_pdf:
    path: /evenement/{id}/pdf
    controller: App\Controller\EvenementController::pdf

qr_code:
    path: /evenement/{id}/qrcode
    controller: App\Controller\EvenementController::qrcode